apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-name
spec:
  selector:
    matchLabels:
      App: ms-name
  template:
    metadata:
      labels:
        App: ms-name
    spec:
      containers:
      - name: ms-name
        image: IMAGE:TAG
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
