apiVersion: v1
kind: Service
metadata:
  name: ms-name
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    App: ms-name
  sessionAffinity: None
  type: ClusterIP
