apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-name
spec:
  template:
    spec:
      containers:
      - name: ms-name
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 100Mi
        env:
          - name: ENV
            value: "staging" 
         