apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
- ingresses.yaml
- hpa.yaml
images:
- name: IMAGE
  newName: ms-image
  newTag: v0.0.1
patches:
  - path: deployment-patch.yaml
